// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Embutidos.Infraestructura.AccesoDatos;

public partial class Productoo
{
    public int id_producto { get; set; }

    public string nombre { get; set; }

    public DateOnly? fecha_fabricacion { get; set; }

    public DateOnly? fecha_caducidad { get; set; }

    public string descripcion { get; set; }

    public int? estado { get; set; }

    public int? id_tipo_producto { get; set; }

    public virtual tipo_producto id_tipo_productoNavigation { get; set; }

    public virtual ICollection<receta> receta { get; set; } = new List<receta>();
}