// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Embutidos.Infraestructura.AccesoDatos;

public partial class receta
{
    public int id_receta { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public int? estado { get; set; }

    public int? id_producto { get; set; }

    public virtual Productoo id_productoNavigation { get; set; }
}