// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Embutidos.Infraestructura.AccesoDatos;

public partial class tipo_producto
{
    public int id_tipo_producto { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public int? estado { get; set; }

    public virtual ICollection<Productoo> Productoo { get; set; } = new List<Productoo>();
}